### ISSUE TITLE
Bug report: 2 follow system themes

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#99] opened 2023-02-01 03:26 UTC
**Expected behavior:** What did you expect to happen when performing these steps?
There should be only one Follow system theme option

**Observed behavior:** What actually happened and why is it a problem? If applicable, consider adding screenshots to help explain.
Currently there are 2 follow system themes. If a the follows system, it should be accordingly, it doesn't need 2 options.

**Device information:** Include your device operating system and version.
Zenfone 6, Android 11
![Screenshot_20230201-034612887 (1).jpg](https://user-images.githubusercontent.com/50620416/215938008-bbe2cc1b-b24c-4447-8f9a-84a97543b422.jpg)

**Comment by ncosgray** [comment] 2023-02-02 02:52
Closing as duplicate of issue #98.

**Closed by ncosgray** 2023-02-02 02:52 UTC
Labels: bug, duplicate
